project:
  type: website
  resources:
    - "CNAME"

website:
  title: "Dokumentace AMČR"
  favicon: figs/cover.png
  repo-url: https://github.com/ARUP-CAS/aiscr-webamcr-help/
  repo-actions: [source, edit, issue]
  page-navigation: true
  google-analytics:
    tracking-id: "G-S3BT2B2SPF"
    anonymize-ip: true
    storage: cookies
  cookie-consent:
    type: express
    style: simple
    palette: light
  bread-crumbs: true

  navbar:
    background: dark
    search: true
    pinned: true
    logo: figs/cover_g.png
    left:
      - text: Úvod
        href: index.qmd
      - text: O systému
        href: o-systemu/index.qmd
      - text: AMČR
        href: amcr/index.qmd
      - text: Digitální archiv AMČR
        href: digiarchiv/index.qmd
      - text: AMČR API
        href: https://ARUP-CAS.github.io/aiscr-api-home
        icon: box-arrow-up-right
        target: _blank
    right:
      - text: Metodiky
        href: metodika/index.qmd
      - text: Slovník pojmů
        href: slovnik/index.qmd
      - text: Zpravodaj
        href: zpravodaj/index.qmd
      - text: Kontakty
        href: about/index.qmd

  sidebar:
    - id: main
      collapse-level: 2
      style: docked
      header: |
        [![](/figs/logo-amcr-hor.png)](/index.qmd)
      contents:
        - index.qmd
        - zakladni-info/zakladni-info.qmd
        - zakladni-info/ucty.qmd
        - text: Zpracování osobních údajů
          href: zakladni-info/osobni-udaje.qmd
        - zakladni-info/historie.qmd
      # footer: |
      #   **{{< fa skull-crossbones >}}  Pozor, zavítali jste na stránky připravované pro novou verzi AMČR!**  
      #   Tyto stránky jsou ve výstavbě a informace, které obsahují, nemusí být platné pro aktuálně spuštěné verze nástrojů AMČR. 
      #   Platná nápověda je [zde](https://amcr-info.aiscr.cz/help).

    - id: o-systemu
      header: |
        [![](/figs/thumb_pin_wrench.png)](/o-systemu/index.qmd)
      contents:
        - o-systemu/index.qmd
        - o-systemu/architektura.qmd
        - o-systemu/datovy-model.qmd
        - o-systemu/role.qmd
        - o-systemu/identifikatory.qmd
        - o-systemu/procesy.qmd
        - o-systemu/heslare.qmd
      

    - id: manual-amcr
      collapse-level: 1
      header: |
        [![](/figs/logo-amcr-hor.png)](/amcr/index.qmd)
      contents:
        - text: Úvod
          href: amcr/index.qmd
        - text: ---
        - section: Návody
          contents: 
            - text: Webová aplikace
              href: amcr/gui.qmd
            - text: Mapové rozhraní
              href: amcr/mapa.qmd
            - text: Oznámení záměru
              href: amcr/oznameni.qmd
            - text: Správa projektů
              href: amcr/projekty.qmd
            - text: Správa akcí
              href: amcr/akce.qmd
            - text: Správa lokalit
              href: amcr/lokality.qmd
            - section: AMČR-PAS
              href: amcr/amcr-pas/index.qmd
              contents:
                # - amcr/amcr-pas/faq-spolupracovnici.qmd
                # - amcr/amcr-pas/faq-archeologove.qmd
                - amcr/amcr-pas/amater.qmd
                - amcr/amcr-pas/archeolog.qmd
            - text: "Správa dokumentů"
              href: amcr/dokumenty.qmd
            - text: "Knihovna 3D"
              href: amcr/knihovna3d.qmd
            - text: "Správa externích zdrojů"
              href: amcr/externi.qmd
        - text: ---
        - section: Tutoriály
          contents:
              - text: Import geometrie PIAN 
                href: amcr/pian-import.qmd
              - text: Zápis správného typu DJ
                href: amcr/dj.qmd
              - text: Akce drobného rozsahu
                href: amcr/drobne-akce.qmd
              - text: Zápis ADB 
                href: amcr/adb.qmd
              - text: Fotografická dokumentace nálezů
                href: amcr/amcr-pas/foto.qmd
              - amcr/lokality-metodika.qmd
              - text: Metodika tvorby plánů na základě šikmých leteckých snímků
                href: https://doi.org/10.5281/zenodo.7925830
                icon: box-arrow-up-right
                target: _blank
              - text: Postup vektorizace objektů na základě šikmých leteckých snímků
                href: https://doi.org/10.5281/zenodo.7925795
                icon: box-arrow-up-right
                target: _blank
            
    - id: manual-digiarchiv
      header: |
        [![](/figs/thumb_digiarchiv.png)](/digiarchiv/index.qmd)  
      contents:
        - section: Návody
          contents:
           - digiarchiv/index.qmd
        - text: "---"
        - section: Tutoriály
          contents:
            - text: Citace dat a dokumentů
              href: digiarchiv/citace.qmd
            - text: Sklízení dat pro GIS
              href: https://zenodo.org/doi/10.5281/zenodo.11490821
              icon: box-arrow-up-right
              target: _blank
      
    # - id: manual-api
    #   contents:
    #     - api/index.qmd
    
    - id: metodika 
      header: |
        [![](/figs/logo-amcr-hor.png)](/metodika/index.qmd)
      contents: 
        - text: Úvod
          href: metodika/index.qmd
        - text: Administrace projektů
          href: metodika/administrace-proj.qmd
        - text: Badatelské výzkumy
          href: metodika/badatelske-vyzkumy.qmd
        - text: AMČR-PAS v kontextu památkového zákona
          href: metodika/amcr-pas.qmd
        - text: Stanovisko Památkové inspekce MK ČR k AMČR-PAS
          href: metodika/docs/AMCR-PAS_MK-CR_stanovisko.pdf
          icon: file-pdf
        - text: Pravidla pro podání NZ
          href: metodika/pravidla-nz.qmd

    - id: pojmy
      contents:
        - slovnik/index.qmd        
        
    - id: zpravodaje 
      header: |
        [![](/figs/logo-amcr-hor.png)](/zpravodaj/index.qmd)
      contents: 
        - zpravodaj/index.qmd
        
    - id: about
      header: |
        [![](/figs/logo-aiscr-hor.png)](/about/index.qmd)
      contents: 
        - about/index.qmd

  page-footer:
    background: light
    left: |
      <a href="/about/index.qmd" class="fttext">Kontakty</a> | 
      <u id="open_preferences_center" class="fttext">Cookies</u> | 
      <span class="fttext">CC BY-NC 4.0</span>
    center: |        
      <a href="https://www.aiscr.cz/" target=_blank><img src="/figs/logo-aiscr-hor.png" height="60"></a>
    right: |
      Vytvořeno s &#9825; v <a href="https://www.quarto.org/" target=_blank>Quarto</a>, 
      zdroj na <a href="https://github.com/ARUP-CAS/aiscr-webamcr-help" target=_blank>GitHub <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 512" width=14 style="fill:#6b6b6b; margin-left:2px;"><!--!Font Awesome Free 6.6.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path d="M165.9 397.4c0 2-2.3 3.6-5.2 3.6-3.3 .3-5.6-1.3-5.6-3.6 0-2 2.3-3.6 5.2-3.6 3-.3 5.6 1.3 5.6 3.6zm-31.1-4.5c-.7 2 1.3 4.3 4.3 4.9 2.6 1 5.6 0 6.2-2s-1.3-4.3-4.3-5.2c-2.6-.7-5.5 .3-6.2 2.3zm44.2-1.7c-2.9 .7-4.9 2.6-4.6 4.9 .3 2 2.9 3.3 5.9 2.6 2.9-.7 4.9-2.6 4.6-4.6-.3-1.9-3-3.2-5.9-2.9zM244.8 8C106.1 8 0 113.3 0 252c0 110.9 69.8 205.8 169.5 239.2 12.8 2.3 17.3-5.6 17.3-12.1 0-6.2-.3-40.4-.3-61.4 0 0-70 15-84.7-29.8 0 0-11.4-29.1-27.8-36.6 0 0-22.9-15.7 1.6-15.4 0 0 24.9 2 38.6 25.8 21.9 38.6 58.6 27.5 72.9 20.9 2.3-16 8.8-27.1 16-33.7-55.9-6.2-112.3-14.3-112.3-110.5 0-27.5 7.6-41.3 23.6-58.9-2.6-6.5-11.1-33.3 2.6-67.9 20.9-6.5 69 27 69 27 20-5.6 41.5-8.5 62.8-8.5s42.8 2.9 62.8 8.5c0 0 48.1-33.6 69-27 13.7 34.7 5.2 61.4 2.6 67.9 16 17.7 25.8 31.5 25.8 58.9 0 96.5-58.9 104.2-114.8 110.5 9.2 7.9 17 22.9 17 46.4 0 33.7-.3 75.4-.3 83.6 0 6.5 4.6 14.4 17.3 12.1C428.2 457.8 496 362.9 496 252 496 113.3 383.5 8 244.8 8zM97.2 352.9c-1.3 1-1 3.3 .7 5.2 1.6 1.6 3.9 2.3 5.2 1 1.3-1 1-3.3-.7-5.2-1.6-1.6-3.9-2.3-5.2-1zm-10.8-8.1c-.7 1.3 .3 2.9 2.3 3.9 1.6 1 3.6 .7 4.3-.7 .7-1.3-.3-2.9-2.3-3.9-2-.6-3.6-.3-4.3 .7zm32.4 35.6c-1.6 1.3-1 4.3 1.3 6.2 2.3 2.3 5.2 2.6 6.5 1 1.3-1.3 .7-4.3-1.3-6.2-2.2-2.3-5.2-2.6-6.5-1zm-11.4-14.7c-1.6 1-1.6 3.6 0 5.9 1.6 2.3 4.3 3.3 5.6 2.3 1.6-1.3 1.6-3.9 0-6.2-1.4-2.3-4-3.3-5.6-2z"/></svg></a>

format:
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    theme:
      light: 
        - spacelab
        # - cosmo
        - theme.scss
    css:
      # - museo.css
      - styles.css
    mainfont: "Alegreya Sans"
    fontsize: 1.1em
    df-print: kable
    link-external-newwindow: true
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 300px
  # pdf:
  #   documentclass: scrarticle
  #   papersize: a4wide
  #   lot: false
  #   lof: false
  # docx: default

execute:
  freeze: false
  echo: false

crossref:
   chapters: true
   tbl-prefix: "Tab."
   tbl-title: "Tab."
   fig-prefix: "Obr."
   fig-title: "Obr."

callout-appearance: simple
# number-sections: false
# number-depth: 1
toc-title: "Na této stránce..."
toc-depth: 4

bibliography: references.bib
# csl: https://www.zotero.org/styles/archeologicke-rozhledy

lang: cs
language:
  related-formats-title: "Stáhnout..."
  section-title-references: "Zdroje"
  title-block-published: "Aktualizováno"
