project:
  type: book

book:
  title: "Nápověda a dokumentace AMČR"
  favicon: "figs/cover.png"
  # cover-image: "cover1.png"

  author: 
    - name: David Novák
      orcid: 0000-0001-6592-6291
      # affiliations:
      #   - id: arup
      #     name: Archeologický ústav AV ČR, Praha, v.v.i.
    - name: Martin Kuna
      orcid: 0000-0001-9244-8387
      # affiliations:
      #   - ref: arup
    - name: Petr Pajdla
      orcid: 0000-0001-7050-9572
      # affiliations:
      #   - id: arub
      #     name: Archeologický ústav AV ČR, Brno, v.v.i.
    - name: Odřej Švejcar
      # affiliations:
      #   - ref: arup
    - name: Tomáš Chlup
      orcid: 0000-0003-3179-992X
      # affiliations:
      #   - ref: arup

  date: today
  date-format: "D. M. YYYY"
  doi: fuu
  license: CC BY-SA 4.0
  language: cs
  type: book
  downloads: [pdf, docx]
  repo-url: https://github.com/ARUP-CAS/aiscr-webamcr-help/
  repo-actions: [source, edit, issue]
  reader-mode: true

  page-footer:
    background: light
    left:
      - icon: github
        href: https://github.com/ARUP-CAS/
      - icon: twitter
        href: https://twitter.com/AISCRproject/
      - icon: facebook
        href: https://www.facebook.com/ArcheologickyInformacniSystem/
    center: |
      [![](figs/AISCR_CZ_H_CMYK_Pozitiv.png){height=50}](https://aiscr.cz/)
    right: |
      Vytvořeno pomocí <a href="https://quarto.org/">Quarto</a>.

  sidebar:
    title: "Dokumentace AMČR"
    # subtitle: Fuu
    logo: "figs/AMCR_cmyk_pozitiv-03.png"
    search: true
    # tools:
    #   - icon: github
    #     href: https://github.com/ARUP-CAS/aiscr-webamcr-help/
    #     text: GitHub
#    footer: |
#      [htpps://aiscr.cz/](https://aiscr.cz/){.external}

  chapters:
    - index.qmd
    - part: "AMČR"
      chapters:
        - historie.qmd
        - pojmy.qmd
        - implementace.qmd
        - role.qmd
        - datovy-model.qmd
        - identifikatory.qmd
        - procesy.qmd
        - heslare.qmd
        - pracovni-postupy.qmd
        - aplikace.qmd
    - part: "Moduly AMČR"
      chapters:
        - pas.qmd
    - part: "Dobrá praxe"
      chapters:
        - dj.qmd
        - drobne-akce.qmd
        - pas-foto.qmd
    - part: "AMČR API"
      chapters:
        - api.qmd
    - zdroje.qmd
#  appendices:
#    - admin.qmd

format:
  html:
    theme:
      light: yeti
      # dark: darkly
    css: styles.css
    df-print: kable
#    link-external-icon: true
    link-external-newwindow: true
    # citation-location: margin
#    title-block-banner: true
  pdf:
    documentclass: scrreprt
    papersize: a4wide
    lot: true
    lof: true
  docx: default

execute:
  freeze: auto
  echo: false

crossref:
  chapters: true
  tbl-prefix: "Tab."
  tbl-title: "Tab."
  fig-prefix: "Obr."
  fig-title: "Obr."

callout-appearance: simple
number-sections: true
number-depth: 1
toc-title: "Obsah"

bibliography: references.bib
csl: https://www.zotero.org/styles/journal-of-computer-applications-in-archaeology
