project:
  type: website
  resources:
    - "CNAME"

website:
  title: "Dokumentace AMČR"
  favicon: figs/cover.png
  repo-url: https://github.com/ARUP-CAS/aiscr-webamcr-help/
  # repo-actions: [source, edit, issue]
  page-navigation: true
  google-analytics:
    tracking-id: "G-S3BT2B2SPF"
    anonymize-ip: true
    storage: cookies
  cookie-consent:
    type: express
    style: simple
    palette: light
  bread-crumbs: true

  navbar:
    background: dark
    search: true
    pinned: true
    logo: figs/cover_g.png
    left:
      - text: Úvod
        href: index.qmd
      - text: O systému
        href: o-systemu/index.qmd
      - text: AMČR
        href: amcr/index.qmd
      - text: Digitální archiv AMČR
        href: digiarchiv/index.qmd
      - text: AMČR API
        href: https://api.aiscr.cz
        icon: box-arrow-up-right
        target: _blank
      - text: Slovník pojmů
        href: slovnik/index.qmd
    right:
      - text: Zpravodaj
        href: zpravodaj/index.qmd
      - text: Kontakty
        href: about/index.qmd

  sidebar:
    - id: main
      collapse-level: 2
      style: "floating"
      header: |
        [![](/figs/logo-amcr-hor.png)](/index.qmd)
      contents:
        - index.qmd
        - zakladni-info/zakladni-info.qmd
        - zakladni-info/ucty.qmd
        - zakladni-info/historie.qmd
      # footer: |
      #   **{{< fa skull-crossbones >}}  Pozor, zavítali jste na stránky připravované pro novou verzi AMČR!**  
      #   Tyto stránky jsou ve výstavbě a informace, které obsahují, nemusí být platné pro aktuálně spuštěné verze nástrojů AMČR. 
      #   Platná nápověda je [zde](https://amcr-info.aiscr.cz/help).

    - id: o-systemu
      header: |
        [![](/figs/thumb_pin_wrench.png)](/o-systemu/index.qmd)
      contents:
        - o-systemu/index.qmd
        - o-systemu/architektura.qmd
        - o-systemu/datovy-model.qmd
        - o-systemu/role.qmd
        - o-systemu/identifikatory.qmd
        - o-systemu/procesy.qmd
        - o-systemu/heslare.qmd
      

    - id: manual-amcr
      header: |
        [![](/figs/logo-amcr-hor.png)](/amcr/index.qmd)
      contents:
        - text: Úvod
          href: amcr/index.qmd
        - text: ---
        - section: Návody
          contents: 
            - text: Webová aplikace
              href: amcr/gui.qmd
            - text: Mapové rozhraní
              href: amcr/mapa.qmd
            - text: Oznámení záměru
              href: amcr/oznameni.qmd
            - text: Správa projektů
              href: amcr/projekty.qmd
            - text: Správa akcí
              href: amcr/akce.qmd
            - text: Správa lokalit
              href: amcr/lokality.qmd
            - section: AMČR-PAS
              href: amcr/amcr-pas/index.qmd
              contents:
                # - amcr/amcr-pas/faq-spolupracovnici.qmd
                # - amcr/amcr-pas/faq-archeologove.qmd
                - amcr/amcr-pas/amater.qmd
                - amcr/amcr-pas/archeolog.qmd
            - text: "Správa dokumentů"
              href: amcr/dokumenty.qmd
            - text: "Knihovna 3D"
              href: amcr/knihovna3d.qmd
            - text: "Správa externích zdrojů"
              href: amcr/externi.qmd
        - text: ---
        - section: Tutoriály
          contents:
              - amcr/amcr-pas/foto.qmd
              - text: Import PIAN z CSV  
                href: amcr/pian-import.qmd
              - amcr/drobne-akce.qmd
              # - text: Zápis správného typu dokumentačních jednotek
              #   href: amcr/dj.qmd
              # - amcr/adb.qmd
              - amcr/lokality-metodika.qmd
              - text: Metodika tvorby plánů na základě šikmých leteckých snímků
                href: https://doi.org/10.5281/zenodo.7925830
                icon: box-arrow-up-right
                target: _blank
              - text: Postup vektorizace objektů na základě šikmých leteckých snímků
                href: https://doi.org/10.5281/zenodo.7925795
                icon: box-arrow-up-right
                target: _blank
            
    - id: manual-digiarchiv
      header: |
        [![](/figs/thumb_digiarchiv.png)](/digiarchiv/index.qmd)  
      contents:
        - section: Návody
          contents:
           - digiarchiv/index.qmd
        - text: "---"
        - section: Tutoriály
          contents:
            - text: Citace dat a dokumentů
              href: digiarchiv/citace.qmd
            - text: Sklízení dat pro GIS
              href: https://zenodo.org/doi/10.5281/zenodo.11490821
              icon: box-arrow-up-right
              target: _blank
      
    # - id: manual-api
    #   contents:
    #     - api/index.qmd

    - id: pojmy
      contents:
        - slovnik/index.qmd
        
    - id: zpravodaje 
      header: |
        [![](/figs/logo-amcr-hor.png)](/zpravodaj/index.qmd)
      contents: 
        - zpravodaj/index.qmd
        
    - id: about
      header: |
        [![](/figs/logo-aiscr-hor.png)](/about/index.qmd)
      contents: 
        - about/index.qmd

  page-footer:
    background: light
    left: |
      [Kontakty](/about/index.qmd) | 
      [<u>Cookies</u>]{#open_preferences_center} |
      CC BY-NC 4.0
    center: |
      [![](/figs/logo-aiscr-hor.png){height=60}](https://aiscr.cz/)
    right: 
      - text: Vytvořeno s &#9825; v Quarto.
        href: https://www.quarto.org/

format:
  html:
    toc: true
    theme:
      - spacelab
      - theme.scss
    css:
      - museo.css
      - styles.css
    mainfont: "Alegreya Sans"
    fontsize: 1.1em
    df-print: kable
    link-external-newwindow: true
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 300px
  # pdf:
  #   documentclass: scrarticle
  #   papersize: a4wide
  #   lot: false
  #   lof: false
  # docx: default

execute:
  freeze: auto
  echo: false

crossref:
   chapters: true
   tbl-prefix: "Tab."
   tbl-title: "Tab."
   fig-prefix: "Obr."
   fig-title: "Obr."

callout-appearance: simple
# number-sections: false
# number-depth: 1
toc-title: "Na této stránce..."
toc-depth: 4

bibliography: references.bib
# csl: https://www.zotero.org/styles/archeologicke-rozhledy

lang: cs
language:
  related-formats-title: "Stáhnout..."
  section-title-references: "Zdroje"
  title-block-published: "Aktualizováno"
