project:
  type: website
  resources:
    - "CNAME"

website:
  title: "Dokumentace AMČR"
  favicon: figs/cover.png
  repo-url: https://github.com/ARUP-CAS/aiscr-webamcr-help/
  repo-actions: [source, edit, issue]
  page-navigation: true
  google-analytics:
    tracking-id: "G-S3BT2B2SPF"
    anonymize-ip: true
    storage: cookies
  cookie-consent:
    style: simple
    palette: light
  bread-crumbs: true

  navbar:
    background: dark
    search: true
    pinned: false
    logo: figs/cover_g.png
    left:
      - text: Úvod
        href: index.qmd
      - text: O systému
        href: o-systemu/o-systemu.qmd
      - text: AMČR
        href: amcr/amcr.qmd
      - text: Digitální archiv AMČR
        href: digiarchiv/digiarchiv.qmd
      - text: AMČR API
        href: api/api.qmd
      - text: Slovník pojmů
        href: o-systemu/pojmy.qmd
    right:
      - text: Zpravodaj
        href: zpravodaj/zpravodaj.qmd
      - text: Kontakty
        href: about.qmd

  sidebar:
    - id: main
      collapse-level: 2
      style: "floating"
      header: |
        [![](/figs/logo-amcr-hor.png)](index.qmd)
      contents:
        - index.qmd
        - zakladni-info/zakladni-info.qmd
        - zakladni-info/ucty.qmd
        - zakladni-info/historie.qmd
      footer: |
        **{{< fa skull-crossbones >}}  Pozor, zavítali jste na stránky připravované pro novou verzi AMČR!**  
        Tyto stránky jsou ve výstavbě a informace, které obsahují, nemusí být platné pro aktuálně spuštěné verze nástrojů AMČR. 
        Platná nápověda je [zde](https://amcr-info.aiscr.cz/help).

    - id: o-systemu
      contents:
        - o-systemu/o-systemu.qmd
        - o-systemu/architektura.qmd
        - o-systemu/datovy-model.qmd
        - o-systemu/role.qmd
        - o-systemu/identifikatory.qmd
        - o-systemu/procesy.qmd
        - o-systemu/heslare.qmd
      header: |
        ![](/figs/thumb_pin_wrench.png)

    - id: manual-amcr
      header: |
        [![](/figs/logo-amcr-hor.png)](/amcr/amcr.qmd)
      contents:
        - text: Úvod
          href: amcr/amcr.qmd
        - text: ---
        - section: Návody
          contents: 
            - text: Webová aplikace
              href: amcr/gui.qmd
            - text: Mapové rozhraní
              href: amcr/mapa.qmd
            - text: Oznámení záměru
              href: amcr/oznameni.qmd
            - text: Správa projektů
              href: amcr/projekty.qmd
            - section: Správa akcí
              href: amcr/akce/akce.qmd
            - section: AMČR-PAS
              href: amcr/amcr-pas/amcr-pas.qmd
              contents:
                - amcr/amcr-pas/faq-spolupracovnici.qmd
                - amcr/amcr-pas/faq-archeologove.qmd
                - amcr/amcr-pas/amater.qmd
                - amcr/amcr-pas/archeolog.qmd
        - text: ---
        - section: Tutoriály
          contents:
              - amcr/amcr-pas/foto.qmd
              - amcr/akce/dj.qmd
              - amcr/akce/drobne-akce.qmd
              - amcr/akce/adb.qmd
            # - text: "Knihovna 3D"
            #   href: amcr/knihovna3d.qmd
            # - section: "Správa lokalit"
            #   contents:
            #     - amcr/lokality/lokality.qmd
            #     - section: "Letecká archeologie"
            #       contents:
            #         - amcr/lokality/plany.qmd
            #         - amcr/lokality/vektorizace.qmd
            # - text: "Správa dokumentů"
            #   href: amcr/dokumenty.qmd
            # - text: "Správa externích zdrojů"
            #   href: amcr/externi.qmd
            # - text: "Administrace systému"
            #   href: amcr/admin.qmd

    - id: manual-digiarchiv
      header: |
        [![](/figs/thumb_digiarchiv.png)](/digiarchiv/digiarchiv.qmd)  
      contents:
        - section: Návody
          contents:
           - digiarchiv/digiarchiv.qmd
        - text: "---"
        - section: Tutoriály
          contents:
            - text: Citace dat a dokumentů
              href: digiarchiv/citace.qmd
            - text: Sklízení dat pro GIS
              href: https://zenodo.org/doi/10.5281/zenodo.11490821
              icon: box-arrow-up-right
              target: _blank
      
    - id: manual-api
      contents:
        - api/api.qmd

    - id: pojmy
      contents:
        - o-systemu/pojmy.qmd
        
    - id: zpravodaje 
      header: |
        [![](/figs/logo-amcr-hor.png)](/zpravodaj/zpravodaj.qmd)
      contents: 
        - zpravodaj/zpravodaj.qmd
        
    - id: about
      header: |
        [![](/figs/logo-aiscr-hor.png)](/about.qmd)
      contents: 
        - about.qmd
        - zakladni-info/licence.qmd

  page-footer:
    background: light
    left: |
      [Kontakty](/about.qmd) | 
      [Licence](/zakladni-info/licence.qmd) | 
      [<u>Cookies</u>]{#open_preferences_center}
    center: |
      [![](/figs/logo-aiscr-hor.png){height=60}](https://aiscr.cz/)
    right: |
      Vytvořeno pomocí <a href="https://quarto.org/">Quarto</a>.

format:
  html:
    toc: true
    theme:
      - spacelab
      - theme.scss
    css:
      - museo.css
      - styles.css
    mainfont: "Alegreya Sans"
    fontsize: 1.1em
    df-print: kable
    link-external-newwindow: true
    # page-layout: full
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 300px
  pdf:
    documentclass: scrarticle
    papersize: a4wide
    lot: false
    lof: false
  docx: default

execute:
  freeze: auto
  echo: false

crossref:
   chapters: true
   tbl-prefix: "Tab."
   tbl-title: "Tab."
   fig-prefix: "Obr."
   fig-title: "Obr."

callout-appearance: simple
# number-sections: false
# number-depth: 1
toc-title: "Na této stránce..."
toc-depth: 4

bibliography: references.bib
# csl: https://www.zotero.org/styles/archeologicke-rozhledy

lang: cs
language:
  related-formats-title: "Stáhnout..."
  section-title-references: "Zdroje"
  title-block-published: "Aktualizováno"
