project:
  type: book

book:

  title: Uživatelská dokumentace AMČR

  favicon: figs/cover.png
  cover-image: figs/AMCR_cmyk_pozitiv-03.png
  date: today
  date-format: D. M. YYYY
  doi: 10.5281/zenodo.8141634
  license: https://creativecommons.org/licenses/by-nc/4.0/
  language: cs
  type: book
  downloads: [pdf]
  repo-url: https://github.com/ARUP-CAS/aiscr-webamcr-help/
  repo-actions: [source, edit, issue]
  reader-mode: true

  author:
    - name: David Novák
      orcid: 0000-0001-6592-6291
      # affiliations:
      #   - id: arup
      #     name: Archeologický ústav AV ČR, Praha, v.v.i.
    - name: Martin Kuna
      orcid: 0000-0001-9244-8387
      # affiliations:
      #   - ref: arup
    - name: Petr Pajdla
      orcid: 0000-0001-7050-9572
      # affiliations:
      #   - id: arub
      #     name: Archeologický ústav AV ČR, Brno, v.v.i.
    - name: Odřej Švejcar
      # affiliations:
      #   - ref: arup
    - name: Tomáš Pavloň
    - name: Tomáš Chlup
      orcid: 0000-0003-3179-992X
      # affiliations:
      #   - ref: arup

  sidebar:
    title: Dokumentace AMČR
    # logo: figs/AMCR_cmyk_pozitiv-03.png
    search: true
    collapse-level: 1
    pinned: true

  chapters:
    - index.qmd

    - part: "AMČR"
      chapters:
        - historie.qmd
        - pojmy.qmd
        - implementace.qmd
        - role.qmd
        - datovy-model.qmd
        - identifikatory.qmd
        - procesy.qmd
        - heslare.qmd
        - pracovni-postupy.qmd
        - aplikace.qmd

    - part: "Moduly AMČR"
      chapters:
        - lokality.qmd
        - pas.qmd
        - pas-archeolog.qmd
        - pas-amater.qmd

    - part: "Dobrá praxe"
      chapters:
        - dj.qmd
        - drobne-akce.qmd
        - adb.qmd
        - pas-foto.qmd

    - part: "AMČR API"
      chapters:
        - api.qmd
    - zdroje.qmd
#  appendices:
#    - admin.qmd

  page-footer:
    background: light
    left:
      - icon: github
        href: https://github.com/ARUP-CAS/
      - icon: twitter
        href: https://twitter.com/AISCRproject/
      - icon: facebook
        href: https://www.facebook.com/ArcheologickyInformacniSystem/
    center: |
      [![](figs/AISCR_CZ_H_CMYK_Pozitiv.png){height=50}](https://aiscr.cz/)
    right: |
      Vytvořeno pomocí <a href="https://quarto.org/">Quarto</a>.

format:
  html:
    theme:
      light: cosmo
      # dark: darkly
    css: styles.css
    df-print: kable
    link-external-newwindow: true
    # citation-location: margin
    # title-block-banner: true
  pdf:
    documentclass: scrreprt
    papersize: a4wide
    # fontfamily: droid
    lot: true
    lof: true
  # docx: default

execute:
  freeze: auto
  echo: false

crossref:
  chapters: true
  tbl-prefix: "Tab."
  tbl-title: "Tab."
  fig-prefix: "Obr."
  fig-title: "Obr."

callout-appearance: simple
number-sections: true
number-depth: 1
toc-title: "Obsah"

bibliography: references.bib
csl: https://www.zotero.org/styles/internet-archaeology
