project:
  type: website

website:
  title: "Uživatelská dokumentace AMČR"
  favicon: figs/cover.png
  repo-url: https://github.com/ARUP-CAS/aiscr-webamcr-help/
  repo-actions: none
  reader-mode: false
  page-navigation: true

  navbar:
    background: dark
    search: true
    pinned: false
    logo: figs/cover_g.png
    left: 
      - index.qmd
      # - zakladni-info/zakladni-info.qmd
      - text: "O systému"
        href: o-systemu/pojmy.qmd
      - manualy/manualy.qmd
    right:
      - text: "Kontakty"
        href: about.qmd

  sidebar:
    - id: main
      collapse-level: 2
      style: "docked"
      header: |
        [![](/figs/logo-amcr-hor.png)](https://amcr-info.aiscr.cz/)
      contents:
        - index.qmd
        - zakladni-info/zakladni-info.qmd
        - zakladni-info/licence.qmd
        - zakladni-info/historie.qmd
            
    - id: o-systemu
      contents:
        - o-systemu/pojmy.qmd
        - o-systemu/datovy-model.qmd
        - o-systemu/role.qmd
        - o-systemu/identifikatory.qmd
        - o-systemu/procesy.qmd
        - o-systemu/heslare.qmd
        
    - id: manualy
      contents:
        - manualy/manualy.qmd
        - section: "AMČR"
          contents:
            - section: "Správa akcí"
              contents: 
                - manualy/dj.qmd
                - manualy/drobne-akce.qmd
                - manualy/adb.qmd
            - section: "AMČR-PAS"
              href: manualy/amcr-pas/pas.qmd
              contents: 
                - manualy/amcr-pas/pas-amater.qmd
                - manualy/amcr-pas/pas-archeolog.qmd
                - manualy/amcr-pas/pas-foto.qmd
            - section: "Správa lokalit"
              contents:
                - manualy/lokality.qmd
        - section: "AMČR API"
          contents: 
            - manualy/api/api.qmd
            
      # - section: "TODO"
      #   contents:
      #     - implementace.qmd
      #     - pracovni-postupy.qmd
      #     - aplikace.qmd

  page-footer:
    background: light
    left: 
      - text: Kontakty
        href: about.qmd
      - text: Licence
        href: zakladni-info/licence.qmd
    center: |
      [![](/figs/logo-aiscr-hor.png){height=60}](https://aiscr.cz/)
    right: |
      Vytvořeno pomocí <a href="https://quarto.org/">Quarto</a>.

format:
  html:
    toc: true
    theme:
      - spacelab # cerulean cosmo flatly lumen spacelab
      - customtheme.scss
    css: 
      - museo.css
      - styles.css
    df-print: kable
    link-external-newwindow: false
    grid: 
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
  pdf:
    documentclass: scrarticle
    papersize: a4wide
    lot: false
    lof: false
  docx: default

execute:
  freeze: auto
  echo: false

crossref:
   chapters: true
   tbl-prefix: "Tab."
   tbl-title: "Tab."
   fig-prefix: "Obr."
   fig-title: "Obr."

callout-appearance: simple
# number-sections: false
# number-depth: 1
toc-title: "Na této stránce..."
toc-depth: 4

bibliography: references.bib
csl: https://www.zotero.org/styles/internet-archaeology

lang: cs
language: 
  related-formats-title: "Stáhnout..."
  section-title-references: "Zdroje"
  
  
