project:
  type: website

website:
  title: "Uživatelská dokumentace AMČR"
  favicon: figs/cover.png
  repo-url: https://github.com/ARUP-CAS/aiscr-webamcr-help/
  repo-actions: none
  reader-mode: false
  page-navigation: true
  google-analytics: "G-S3BT2B2SPF"

  navbar:
    background: dark
    search: true
    pinned: false
    logo: figs/cover_g.png
    left: 
      - text: "Úvod"
        href: index.qmd
      - text: "O systému"
        href: o-systemu/architektura.qmd
      - text: "AMČR"
        href: manualy/manualy.qmd
      - text: "Digitální archiv AMČR"
        href: manualy/digiarchiv/digiarchiv.qmd
      - text: "AMČR API"
        href: manualy/api/api.qmd
      - text: "Slovník pojmů"
        href: o-systemu/pojmy.qmd
    right:
      - text: "Kontakty"
        href: about.qmd

  sidebar:
    - id: main
      collapse-level: 1
      style: "docked"
      header: |
        [![](/figs/logo-amcr-hor.png)](https://amcr-info.aiscr.cz/)
      contents:
        - index.qmd
        - zakladni-info/zakladni-info.qmd
        - zakladni-info/ucty.qmd
        - zakladni-info/historie.qmd
        - zakladni-info/licence.qmd
            
    - id: o-systemu
      contents:
        - o-systemu/architektura.qmd
        - o-systemu/datovy-model.qmd
        - o-systemu/role.qmd
        - o-systemu/identifikatory.qmd
        - o-systemu/procesy.qmd
        - o-systemu/heslare.qmd
        
    - id: manual-amcr
      contents:
        - manualy/manualy.qmd
        - text: "Oznámení záměru"
          href: manualy/zamer.qmd
        - text: "Správa projektů"
          href: manualy/projekty.qmd
        - section: "Správa akcí"
          contents: 
            - manualy/amcr/dj.qmd
            - manualy/amcr/drobne-akce.qmd
            - manualy/amcr/adb.qmd
        - section: "AMČR-PAS"
          contents: 
            - manualy/amcr-pas/pas-faq.qmd
            - manualy/amcr-pas/pas-amater.qmd
            - manualy/amcr-pas/pas-archeolog.qmd
            - manualy/amcr-pas/pas-foto.qmd
        - text: "Knihovna 3D"
          href: manualy/knihovna3d.qmd
        - section: "Správa lokalit"
          contents:
            - manualy/lokality/lokality.qmd
            - manualy/lokality/plany.qmd
            - manualy/lokality/vektorizace.qmd
        - text: "Správa dokumentů"
          href: manualy/dokumenty.qmd
        - text: "Správa externích zdrojů"
          href: manualy/externi.qmd
        - text: "Administrace systému"
          href: manualy/admin.qmd
    
    - id: manual-digiarchiv
      contents:
        - manualy/digiarchiv/digiarchiv.qmd
    
    - id: manual-api
      contents: 
        - manualy/api/api.qmd
        
    - id: pojmy
      contents: 
        - o-systemu/pojmy.qmd

  page-footer:
    background: light
    left: 
      - text: Kontakty
        href: about.qmd
      - text: Licence
        href: zakladni-info/licence.qmd
    center: |
      [![](/figs/logo-aiscr-hor.png){height=60}](https://aiscr.cz/)
    right: |
      Vytvořeno pomocí <a href="https://quarto.org/">Quarto</a>.

format:
  html:
    toc: true
    theme:
      - spacelab
      - customtheme.scss
    css: 
      - museo.css
      # - styles.css
    mainfont: "Figtree"
    df-print: kable
    link-external-newwindow: true
    grid: 
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px
  pdf:
    documentclass: scrarticle
    papersize: a4wide
    lot: false
    lof: false
  docx: default

execute:
  freeze: auto
  echo: false

crossref:
   chapters: true
   tbl-prefix: "Tab."
   tbl-title: "Tab."
   fig-prefix: "Obr."
   fig-title: "Obr."

callout-appearance: simple
# number-sections: false
# number-depth: 1
toc-title: "Na této stránce..."
toc-depth: 4

bibliography: references.bib
csl: https://www.zotero.org/styles/internet-archaeology

lang: cs
language: 
  related-formats-title: "Stáhnout..."
  section-title-references: "Zdroje"
  
