# Hesláře

Data AMČR jsou z větší části strukturována pomocí standardizovaných heslářů (číselníků). Hesláře jednoznačně nastavují sledovanou míru obecnosti/detailu, urychlují zápis typických informací, usnadňují vyhledávání, umožňují data strojově analyzovat a propojovat s dalšími systémy. Díky heslářům je také dodržována jednotná terminologie na území ČR, která vede ke snadnější orientaci ve vznikajících datech.

Hesláře dělíme na jednoduché a dvojstupňové. Jednoduché hesláře obsahují jednu řadu hesel, z nichž uživatel vybírá, ale mohou též obsahovat další dílčí pomocné informace pro zápis (např. zobrazení okresu u katastru). Dvojstupňové hesláře obsahují hierarchicky uspořádaná hesla, z nichž obecnější kategorie slouží pro usnadnění výběru a do záznamu se neukládá (Areály, Druh lokality), nebo se ukládají hesla obě (obecnější i specifické: viz např. Kategorie a Druh nálezu). Charakteru heslářů odpovídají typy výběrových seznamů v aplikaci. Některé hesláře chápeme jako „systémové“ – nelze je editovat bez zásahu do zdrojového kódu, jelikož na nich přímo závisí chování aplikace a specifické funkce.

Obsažená hesla vycházejí z hesel užívaných v ADČ (Kuna – Křivánková 2006), SAS (Volfík 2009) a formulářích ZAA. Systém odborných heslářů se opírá o standardní archeologickou terminologii a obsažena jsou taková hesla, u nichž lze předpokládat vyšší než výjimečné zastoupení na základě analýzy stávajících dat. Aplikace obecně preferuje uzavřené hesláře, jejichž doplnění je možné pouze v důvodných případech po konzultaci se správcem systému. Výjimku tvoří heslář jmen, u něhož lze předpokládat pravidelný nárůst počtu údajů a lze jej proto uživatelsky doplňovat (tlačítko Nové jméno ve formulářích).

Hesláře AMČR vytvářejí svým obsahem základ jednotné oborové terminologie, který je aplikován pro popis všech archeologických výzkumů v ČR evidovaných archivy ARÚP a ARÚB. Aktuální obsah všech heslářů je dostupný na webové adrese http://www.archeologickamapa.cz/?page=documents.

Hesláře obvykle obsahují pole „pořadí“, pro určení pořadí položek v seznamu. Řazení může být abecední, případně chronologické (Období), vyskytují se však také případy řazení významového (Nálezy), případně na základě četnosti užívání (Typ projektu). Některé z heslářů mohou obsahovat pole „rozsah“ či „zahrnuje“, která udávají hierarchický vztah hesel, který je zohledněn v modulu vyhledávání (viz obrázek). Obecná hesla jsou často doplněna zkratkou „nesp.“ s významem „blíže nespecifikováno“.

Hesláře Areály a Období umožňují provádět popis komponent pomocí obecnějších i konkrétnějších pojmů (např. pojem „sídliště nesp.“ zahrnuje též pojmy „stanice“, „usedlost“ a „vesnice“). Heslář Období obsahuje 135 chronologických pojmů v daných hierarchických vztazích. Každému pojmu odpovídá číselná hodnota stanovující jeho pořadí v chronologickém systému a číselně stanovený rozsah. Vyhledávat pomocí tohoto hesláře lze buď podle jednoho hesla, nebo zadáním rozsahu, přičemž dále je možno volit všechny hierarchicky nižší (zahrnuté) pojmy a/nebo pojmy nadřazené (např. při výběru pojmu „střední doba bronzová“ lze zohlednit i pojem „doba bronzová nesp.“, protože komponenty charakterizované tímto pojmem rovněž teoreticky mohou se střední dobou bronzovou souviset (více viz Období).
