---
title: Metodický výklad AMČR-PAS v kontextu zákona č. 20/1987 Sb., o státní památkové péči
# subtitle: 
date: 2025-09-15
# date: 2021-03-31
# date: 2025-08-06
description: Verze v1, platná od 31. 3. 2021
format: 
  html: default
  pdf: 
    pdf-engine: xelatex
# reference-location: margin
---

Cílené vyhledávání předmětů, které již neslouží svému původnímu účelu a mohou nést nepsané
informace o minulém lidském světě, naplňuje definici archeologického výzkumu.[^1] 
Vyhledávání může nabývat řady forem, od povrchového sběru po průzkumy využívajících různé druhy detekčních zařízení.
Provádění archeologických výzkumů vždy podléhá regulaci podle zákona č. 20/1987 Sb., o státní památkové péči.

[^1]: Jak potvrzuje [Stanovisko Ministerstva kultury, odboru památkové péče, č.j. 9711/2007](https://www.mkcr.cz/doc/cms_library/2007_09711-3407.doc){.external}.

AMČR-PAS slouží k evidenci málo destruktivních archeologických výzkumů prováděných extenzivně na
velkých plochách, a to zejména za účasti laické veřejnosti, tzv. amatérských spolupracovníků
oprávněných archeologických organizací.

AMČR-PAS respektuje závazky vyplývající z [Evropské úmluvy o ochraně archeologického dědictví č. 99/2000 Sb.m.s.](https://www.zakonyprolidi.cz/ms/2000-99){.external}, která v čl. 3 odst. 3 zavazuje Českou republiku *„učinit používání detektorů kovů a jakýchkoli jiných detekčních zařízení nebo postupů archeologického výzkumu předmětem specifického předchozího oprávnění, kdykoli s tím počítá vnitřní právní úprava státu“*.
Je třeba konstatovat, že důvodů pro užití detektoru může být více, např. pyrotechnický průzkum, vyhledávání inženýrských sítí či hledání ztracených předmětů. 
Ve většině těchto případů nepředstavuje použití detekčního zařízení zvláštní hrozbu pro archeologické dědictví. 
Případy nepředvídaných nálezů při těchto činnostech jsou adekvátně upraveny zákonem v §23.

Tento dokument popisuje vztah AMČR-PAS k jednotlivým ustanovením zákona č. 20/1987 Sb. a slouží jako metodický výklad ze strany Archeologických ústavů AV ČR.


### Užívané pojmy

#### Průzkum 

Průzkum je zaveden jako nový typ archeologického výzkumu vedle záchranného a badatelského výzkumu. 
Z hlediska ustanovení zákona č. 20/1987 Sb. se na průzkum pohlíží jako na archeologický výzkum a při jeho provádění je třeba dodržovat všechny náležitosti stanovené zákonem pro archeologický výzkum. 
Při průzkumu jsou používány nedestruktivní nebo málo destruktivních metody archeologického výzkumu (zejména průzkum detektory kovů a povrchové sběry). 
Průzkum je určen pro lokality či větší územní celky dlouhodobě ohrožené přirozenou degradací terénu, zemědělskou činností či nelegálními aktivitami hledačů.
Průzkum je určen pro preventivní záchranu ohrožených movitých památek, vesměs již zbavených svého původního kontextu uložení. 

Provádění průzkumu **není vhodné pro území prohlášená za kulturní památku, národní kulturní památku, památkovou rezervaci nebo památkovou zónu.** 
V případě průzkumu na památkově chráněných objektech a územích je vyžadován postup v režimu badatelského výzkumu tak, jak je upraven v dohodách o rozsahu a podmínkách provádění archeologických výzkumů uzavřených mezi oprávněnou organizací a Akademií věd ČR[^2]. 
Ve zbylých případech je realizace průzkumu vázána na oznámení záměru Archeologickému ústavu AV ČR prostřednictvím administrace projektu v AMČR.
Postup realizace všech archeologických výzkumů, které nebyly vyvolány stavební či jinou činností dle [§ 22 odst. 2 zákona č. 20/1987 Sb., o státní památkové péči](https://www.zakonyprolidi.cz/cs/1987-20#p22){.external} naleznete v metodickém pokynu k [badatelským výzkumům](badatelske-vyzkumy.qmd).

[^2]: I v případě badatelských archeologických výzkumů lze AMČR-PAS využít pro evidenci movitých nálezů.


#### Amatérský spolupracovník

Amatérský spolupracovník je osobou, která v zájmu výzkumu, poznávání a ochrany archeologického dědictví spolupracuje s oprávněnou organizací. 
Pro spolupracovníka není požadováno formální vzdělání v oboru archeologie. 
Spolupracovník může být v závislosti na úrovni odborných znalostí a schopností pověřován při provádění průzkumu samostatnými úkoly. 
Konkrétní formu a rozsah těchto úkolů stanovuje vedoucí archeologického výzkumu. 
Jedná se zejména o vyhledávání, vyzvedávání a dokumentaci archeologických nálezů zbavených svého původního kontextu uložení. 
Rozsah a způsob spolupráce je upraven dohodou mezi spolupracovníkem a oprávněnou organizací. 
Tato dohoda je uzavírána podle ustanovení § 1724 a násl. [zákona č. 89/2012 Sb., občanský zákoník](https://www.zakonyprolidi.cz/cs/2012-89){.external}, ve znění pozdějších předpisů. 
Podmínky činnosti spolupracovníka mohou být upraveny i v rámci pracovněprávního vztahu[^3].

[^3]: Při srovnání s režimem obvyklým při provádění záchranných archeologických výzkumů lze postavení spolupracovníka srovnat s osobami na úrovni dokumentátora nebo technika v závislosti na úrovni odborných znalostí a schopností.

#### Vedoucí výzkumu

Vedoucí výzkumu je osoba s odbornou kvalifikací archeologa, která je oprávněnou organizací pověřena vedením archeologického výzkumu. 
Stanovuje metodiku výzkumu a uděluje pokyny osobám, které se na výzkumu podílejí.


## Výklad ve vztahu k ustanovením zákona č. 20/1987 Sb., o státní památkové péči

### §21

Veškeré činnosti prováděné v rámci AMČR-PAS probíhají v režimu archeologického výzkumu, který provádí oprávněná organizace. 
Zahájení každého výzkumu oznamuje oprávněná organizace prostřednictvím Archeologické mapy České republiky (dále jen [AMČR](https://amcr.aiscr.cz/){.external} Archeologickému ústavu a podává mu též zprávu o jeho výsledcích ve formě nálezové zprávy ([vzor](amcr/amcr-pas/docs/AMCR-PAS_NZ_vzor.docx)).

Prvním krokem při evidenci je vytvoření projektu v AMČR v kategorii **průzkum**.
Každý průzkum je evidován pod unikátním číslem přiděleným automaticky v AMČR. 
Za provádění průzkumu odpovídá oprávněná organizace, která stanoví metodický postup i časové a prostorové vymezení průzkumu. 
Pro každý průzkum musí být vypracována projektová dokumentace podle [jednotného vzoru](amcr/amcr-pas/docs/AMCR-PAS_projekt_vzor.docx). 
Ta je uložena v AMČR jako součást projektu.

### §22

Při provádění průzkumu je odpovědností oprávněné organizace zajistit uzavření dohody s vlastníkem (správcem, uživatelem) nemovitosti, na které bude průzkum prováděn. 
Je zcela v kompetenci oprávněné organizace rozhodnout, koho vyjednáním dohody pověří a jakou formu (ústní, písemná) bude dohoda mít.

### §23

Archeologické nálezy získané při průzkumu jsou podle [§23](https://www.zakonyprolidi.cz/cs/1987-20#p23){.external}a vlastnictvím kraje, obce nebo státu.
Jednotlivé archeologické nálezy jsou proto od momentu exkavace/vyzvednutí evidovány. 
Při zápisu do AMČR-PAS je každému nálezu přiděleno unikátní přírůstkové číslo, které se skládá z čísla projektu a pořadového čísla
nálezu (např. C-202100001-N00001).

V případech, kdy dojde k nálezu za nepřítomnosti vedoucího výzkumu, je spolupracovník povinen nález předat vedoucímu výzkumu bez zbytečných odkladů, nejpozději však při pravidelné schůzce podle dohody uzavřené mezi spolupracovníkem a oprávněnou organizací. 
O dalším nakládání s movitými nálezy (postup další evidence, selekce) rozhoduje oprávněná organizace.
Na movité nálezy získané v rámci průzkumu se nevztahuje ustanovení podle [§23](https://www.zakonyprolidi.cz/cs/1987-20#p23){.external} odst. 4, a proto nálezce nemá právo na vyplacení odměny.

### §24

Přestože metody aplikované při průzkumu počítají s minimálními destruktivními zásahy, je třeba respektovat práva a oprávněné zájmy vlastníků (správců, uživatelů) nemovitostí, popřípadě jiného majetku, a případným škodám předcházet. 
Je rovněž třeba počítat s možností, že vlastník (správce, uživatel) může vůči oprávněné organizaci uplatnit své nároky za majetkovou újmu.

----

### Dokumenty ke stažení

Vzor nálezové zprávy pro projekty typu průzkum ([DOCX {{< bi file-earmark-arrow-down >}}](/amcr/amcr-pas/docs/AMCR-PAS_NZ_vzor.docx))  
Vzor projektové dokumentace pro projekty typu průzkum ([DOCX {{< bi file-earmark-arrow-down >}}](/amcr/amcr-pas/docs/AMCR-PAS_projekt_vzor.docx))
