---
title: FAQ Spolupracovníci
subtitle: Často kladené otázky amatérských spolupracovníků a veřejnosti
toc-depth: 2
date: 2022-05-03
---

## Proč nemůžu hledat sám?

**Proč bych měl spolupracovat s archeologem?**

Archeologický výzkum může provádět jen organizace k tomu oprávněná, tj. taková, která má povolení Ministerstva kultury České republiky a smlouvu s Akademií věd České republiky (seznam organizací). Neoprávněné provádění archeologického výzkumu je podle zákona přestupkem, za který lze uložit sankci až do výše 4 mil. Kč. Kromě tradičních, plošných výzkumů, je archeologickým výzkumem také např. povrchový sběr či detektorový průzkum. Movité archeologické nálezy nejsou předmětem soukromého vlastnictví, ale výhradně majetkem kraje, obce, nebo státu. Samostatné hledání a držba artefaktů je proto protiprávní činností. Naopak, kontrolovaná spolupráce v souladu s právními předpisy je přínosem jak pro amatéry, tak i pro archeology; zejména však poslouží k vhodnému nakládání s archeologickým dědictvím České republiky.

Archeologie je vědní disciplína, která vyžaduje použití odborných metod, a to nejen na plošném výzkumu, ale také v rámci nedestruktivních či mírně destruktivních průzkumů. K archeologickým nálezům se vážou tzv. nálezové okolnosti, tedy informace o jejich původu, významu, účelu či důvodu uložení na konkrétním místě. Tyto informace jsou pro vědecké bádání naprosto nepostradatelné, ale hlavně také neobnovitelné. Po jejich zničení informace nenávratně mizí a kulturně-historická hodnota nálezu se snižuje. Oprávněná organizace své spolupracovníky náležitě zaškolí tak, aby k takovým ztrátám nedocházelo. Zároveň jasně vymezí, kde a za jakých podmínek je hledání přípustné.

## Jaký je účel AMČR-PAS?

**Je AMČR-PAS v souladu s platnými právními předpisy?**

Archeologická mapa ČR je oborovým nástrojem pro sběr, administraci a archivaci dat získaných terénními archeologickými výzkumy. Modul AMČR-PAS byl speciálně vytvořen pro evidenci dat, která pocházejí z detektorových průzkumů a povrchových sběrů prováděných oprávněnými archeologickými organizacemi a jejich oficiálními spolupracovníky z řad veřejnosti (tzv. občanský či dobrovolný spolupracovník). Z povahy věci není pochyb o legálnosti systému jako takového. AMČR-PAS slouží jako nástroj pro jednotný sběr a uchování dat pocházejících z archeologických průzkumů, na kterých se v rámci platných právních předpisů pod garancí archeologů podílejí amatéři.

## Je používání AMČR-PAS povinné?

**Proč bych měl používat AMČR-PAS?**

Legálně spolupracovat s archeologickými pracovišti na detektorových průzkumech lze výhradně v rámci platných právních předpisů, tedy pouze v rámci oprávněného archeologického výzkumu, a to bez ohledu na uplatnění AMČR-PAS. Jak bylo v předchozí otázce uvedeno, AMČR-PAS je především oborovým nástrojem, který byl vyvinut přímo na míru povrchovým průzkumům. Jeho výhodou pro odborné archeologické instituce je, že umožňuje průběžnou digitální komunikaci se spolupracovníky a také snadnější zpracování a vyhodnocování jimi získaných dat. Výhody samozřejmě nabízí i spolupracovníkům z řad veřejnost, kteří užíváním AMČR-PAS získají možnost dostávat k jednotlivým svým nálezům přehlednou a rychlou zpětnou vazbu. Mohou je kdykoliv zpětně dohledat a všechny zobrazit ve formě vlastní obrazové galerie v Digitálním archivu AMČR.

Základní podmínkou využívání AMČR-PAS spolupracovníky z řad veřejnosti je, že uživatel je legálním spolupracovníkem některé z organizací oprávněných k provádění archeologických výzkumů na daném území. S archeologickými pracovišti samozřejmě lze v současné době spolupracovat i bez používání AMČR-PAS a řada lidí tak již delší dobu činí. Nově vytvořený modul dosud ani všechny odborné organizace nemusí plně využívat. Předpokládáme, že se tento stav postupně změní a používání AMČR-PAS se v rámci oprávněných organizací stane standardem. Forma zapojení spolupracovníků do AMČR-PAS je plně v kompetenci jednotlivých organizací a je třeba vzájemné dohody v rámci komunikace s příslušnými odbornými pracovníky.

## S kterým archeologem nebo organizací mám spolupracovat?

Každá oprávněná organizace má svoji územní působnost, ve které může provádět archeologické výzkumy. Jejich přehled lze najít na Mapě archeologických organizací. Pouze na tomto území může spolupracovat se zájemci z řad veřejnosti a pouze z tohoto území může získávat archeologické nálezy. Proto je vhodné vybírat a oslovovat s nabídkou spolupráce oprávněnou organizaci na základě územní působnosti. Zároveň je třeba mít na paměti, že ne všechna archeologická pracoviště jsou schopna podporu amatérským hledačům nabídnout (zejména z kapacitních a organizačních důvodů či kvůli svému specifickému zaměření). Ne všechny oprávněné organizace se na detektorové prospekce specializují a ne všechny dokážou movité archeologické nálezy adekvátně dlouhodobě spravovat. Obecně lze větší otevřenost vůči spolupracovníkům z řad veřejnosti předpokládat spíš u muzeí či jiných příspěvkových organizací, nebo u Archeologických ústavů AV ČR. Vaše spolupráce s oprávněnou organizací by měla být pravidelná, dlouhodobá a koordinovaná, proto při výběru zohledněte i dosažitelnost sídla organizace z Vašeho bydliště.

## Co když se mnou archeolog nechce spolupracovat?

Jak již bylo řečeno, ne všechny odborné instituce disponují stejnými možnostmi a podmínkami pro spolupráci. Jejich možnosti se mohou také lišit např. dle aktuální vytíženosti. V takovém případě lze oslovit jinou oprávněnou organizaci v okolí. Prakticky v každém regionu je vždy více než jedna organizace, která je oprávněná archeologické výzkumy provádět.

Je třeba mít na paměti, že ke vzniku vzájemné a dlouhodobé spolupráce je zapotřebí oboustranného zájmu a zejména pochopení pro oborová pravidla ze strany spolupracovníků. Jelikož mnoho hledačů provádí tuto činnost nelegálně, je důležité, aby panovala mezi spolupracovníkem a archeologem vzájemná důvěra a přesvědčení, že spolupráce bude probíhat v souladu se zákonem a nebude ohrožovat kulturní dědictví. Hledač by tak v zájmu zachování spolupráce měl dbát na dodržování všech stanovených pravidel.

## Jakou formu bude mít naše spolupráce? 

**Co by měla obsahovat dohoda o spolupráci mezi archeologem a amatérem?**  
**Jakou by měla mít formu?**

Spolupráce by měla probíhat primárně na základě dohody o spolupráci. Pro dohodu je z důvodu transparentnosti důrazně doporučována písemná forma. Mezi náležitosti dohody patří:
- Jednoznačná identifikace spolupracovníka (potvrzení o spolupráci je nepřenosné)
- Stanovení územního a časového rozsahu spolupráce
- Stanovení organizačních pravidel odevzdávání nálezů a komunikace archeologa a spolupracovníka
- Kontaktní údaje spolupracovníka a archeologa (telefon, e-mail, atp.)

Vzor dohody o spolupráci lze najít zde: stáhnout

## Jak v praxi probíhá spolupráce a terénní průzkum?

Po uzavření dohody je spolupracovník proškolen v metodách provádění průzkumu a ošetření nálezů. Tato pravidla musí spolupracovník pečlivě dodržovat. V rámci školení by měla též proběhnout komunikace o tom, na jakém území a jakými metodami spolupracovník může svou činnost vyvíjet. Současně může být spolupracovník proškolen též ve využívání modulu AMČR-PAS.

Před zahájením průzkumu musí spolupracovník informovat majitele pozemku o zájmu provést archeologický průzkum a dohodnout se s ním na podmínkách. Bez (alespoň ústní) dohody a souhlasu majitele pozemku nelze průzkum provést.

Všechny artefakty, které spolupracovník najde, musí být předány archeologovi územně příslušné organizace. Ten vyhodnotí, které z nich spadají do kategorie archeologických nálezů. Archeologické nálezy jsou majetkem kraje, obce nebo státu. Všechny nálezy musí spolupracovník odevzdat na tom pracovišti, kde má uzavřenou dohodu a v rámci jehož projektu svou činnost vyvíjí.

Pokud při hledání narazíte na specifický materiál, jako jsou palné zbraně a střelivo vyrobené po r. 1890, případně lidské ostatky, průzkum okamžitě ukončete a kontaktujte odpovědného archeologa. V případě zbraní a střeliva kontaktujte též Policii ČR.

## Jak se prokážu, že spolupracuji s archeologem?

Každý spolupracovník se musí na žádost majitele pozemku, Policie ČR či jiných oprávněných osob prokázat potvrzením o spolupráci. Potvrzení musí obsahovat prostorové vymezení oblasti průzkumu, základní identifikaci osoby (jméno příjmení, rok narození), pro kterou bylo potvrzení vydáno a dobu platnosti. Dále musí obsahovat přímý (ideálně neustále funkční) kontakt na odpovědného archeologa. Ohledně vydání potvrzení se informujte u oprávněné organizace. Mějte na paměti, že toto potvrzení spolu s průkazem totožnosti jsou jediný způsob jak na místě prokázat, že se nedopouštíte nelegální činnosti.
Na co si musím dát pozor při zápisu nálezu do AMČR-PAS?

Návod na zápis nálezu naleznete na adrese: https://doi.org/10.5281/zenodo.4114081

Nálezy do AMČR-PAS je ideální zapisovat hned na místě jejich učinění. V každém případě je nezbytné správně zaznamenat jejich polohové souřadnice, evidenční číslo a hloubku hned v terénu (ať již přímo do AMČR-PAS či na jiný datový nosič). Ostatní údaje lze do systému zapisovat i zpětně, nejlépe po návratu z prospekce.

V případě, že se spolupracovník účastní více projektů, je nutné klást zvýšený důraz na správnou volbu projektu, pod který nález spadá. O správném zápisu rozhoduje odpovědný archeolog.

## Co se stane s nálezy, které vložím do AMČR-PAS?

Data (zejména nálezy) vložená do AMČR-PAS jsou průběžně zveřejňována v Digitálním archivu AMČR, kde jsou informace o nálezech dostupné zejména vědecké obci, ale také za určitých podmínek široké veřejnosti. Obecně platí, že nálezy učiněné prostřednictvím detektorové prospekce jsou nedílnou součástí kulturního dědictví ČR a přístup k nim je základním lidským právem (čl. 34 a 35 Listiny základních práv a svobod). Právě to Digitální archiv AMČR umožňuje. Rozsah zveřejněných informací nicméně nastavuje archeolog, s nímž uživatel AMČR-PAS spolupracuje a který je zodpovědný za projekt, v jehož rámci spolupracovník svou činnost vykonává. Je plně v jeho kompetenci, aby některé informace (zejména místo nálezu) byly zpřístupněny pouze v takové podobě, která nemůže znamenat ohrožení dalších movitých či nemovitých archeologických památek, např. nelegálním vykrádáním.

## Náleží mi za nálezy odměna?

Zákon č. 20/1987 Sb., o státní památkové péči, ve znění pozdějších předpisů, přiznává nárok na odměnu pouze v případě náhodného nálezu (§ 23). Tedy například v případě nálezu učiněného při provádění zahradních, nebo zemědělských prací.

Nárok na odměnu se nevztahuje na nález učiněný v průběhu aktivního hledání nálezů. V takovém případě se již jedná o archeologický výzkum. V případě že takový výzkum není oprávněný (prováděný archeologickou organizací, schválený a evidovaný v AMČR), jedná se naopak o spáchání přestupku (§ 39 odst. 2 písm. f) zákona o státní památkové péči). Místo odměny tak může být hledači uložena finanční sankce až do výše 4 mil. Kč a také sankce zabavení věci použité ke spáchání přestupku (např. detektor kovů).

 
