---
title: "Uživatelská příručka AMČR"
subtitle: "Úvod"
toc: true
format-links: false
# listing:
#   - id: amcr
#     sort-ui: false
#     filter-ui: false
#     template: ../tiles.ejs
#     contents: 
#       - "projekty.qmd"
#       - "akce/*.qmd"
      
#   - id: pas
#     template: ../tiles.ejs
#     contents:
#       - "amcr-pas/*.qmd"
      
#   - id: lok
#     template: ../tiles.ejs
#     contents:
#       - "lokality.qmd"
---

## Návody

*Návody* ukazují základní pracovní postupy v aplikaci AMČR.

 - [Formulář oznámení](oznameni.qmd) -- jak odeslat oznámení o stavebním či jiném záměru prováděném na území s archeologickými nálezy
 - [Správa Projektů v AMČR](projekty.qmd)

**Správa AMČR-PAS**  
Návody k používání *Portálu amatérských spolupracovníků a evidence samostatných nálezů* ([AMČR-PAS](https://amcr-info.aiscr.cz/pas){.external}). 

- [Úvodní stránka nápovědy k AMČR-PAS](amcr-pas/amcr-pas.qmd) se vzorovými dokumenty ke stažení aj.
- Často kladené otázky (FAQ) [spolupracovníků](amcr-pas/faq-spolupracovnici.qmd) a [archeologů](amcr-pas/faq-archeologove.qmd)
- Návod pro [spolupracovníky](amcr-pas/amater.qmd) a [archeology](amcr-pas/archeolog.qmd)


## Tutoriály 

*Tutoriály* dokumentaují konkrétní postupy, jak dosáhnout určitého cíle, např. správně zapsat dokumentační jendotku, nafotit drobný nález apod.

#### Zápis dokumentačních jednotek 

- [Pokyny pro volbu a zápis správného typu dokumentačních jednotek](akce/dj.qmd)
- [Návod k zápisu Archeologických dokumentačních bodů (ADB) v rámci Pražské památkové rezervace](akce/adb.qmd)

#### AMČR-PAS 

- Jak provádět [fotografickou dokumentaci nálezů](amcr-pas/foto.qmd) pro AMČR-PAS

- [Postup pro zpracování nálezových zpráv z archeologických akcí drobného rozsahu](akce/drobne-akce.qmd)




<!-- ::: {#amcr .column-screen-inset-right}
::: -->




<!-- ::: {#pas .column-screen-inset-right}
::: -->

<!-- ## Knihovna 3D

- [Správa Knihovny 3D](knihovna3d.qmd)

## Lokality

- [Zásady evidence nemovitých archeologických památek (lokalit)](lokality/lokality.qmd)

### Letecká archeologie

- [Metodika tvorby plánů archeologických objektů na základě šikmých leteckých snímků pro potřeby AMČR](lokality/plany.qmd)
- [Postup vektorizace archeologických objektů na základě šikmých leteckých snímků pro potřeby AMČR](lokality/vektorizace.qmd) -->

<!-- ::: {#lok .column-screen-inset-right}
::: -->
