---
title: "Akce drobného rozsahu"
subtitle: "Postup pro zpracování nálezových zpráv z archeologických akcí drobného rozsahu"
---

::: {.callout-important}

## Upozornění

Následující stránka k 1. červenci 2024 neprošla revizí a informace, které obsahuje, nemusí být plně platné pro aktuálně spuštěné verze nástrojů AMČR.
Zároveň mohou být některé odkazy, které stránka obsahuje nefunkční, screenshoty ze zastaralých verzí nástrojů apod.  

:::

Zpracování pozitivních archeologických výzkumů do podoby [nálezové zprávy](pojmy.qmd#nálezová-zpráva) (NZ) se řídí *Pravidly pro podání nálezové zprávy o terénním archeologickém výzkumu* (viz stránky ARÚ [Praha](https://www.arup.cas.cz/wp-content/uploads/2020/05/pravidla_NZ_obecna_191009.pdf){.external} a [Brno](https://arub.cz/wp-content/uploads/Pravidla-pro-podani-nalezove-zpravy-o-terennim-archeologickem-vyzkumu_3_2020.pdf){.external}).

V případě [akcí](pojmy.qmd#akce) drobnějšího rozsahu je v AMČR akceptován i dokument, který nemá podobu plnohodnotné NZ, ale je redukován např. do podoby *Hlášení o archeologické akci* atp.
V některých případech může být záznam i zcela bez přiloženého dokumentu pouze s popisem ve formuláři v AMČR.
I v těchto případech by měl přiložený dokument (nebo popis v AMČR) splňovat následující minimální požadavky.

- Hlavičku dokumentu či titulní stranu s identifikátorem akce z AMČR -- viz vzor výše.
- Úplný popis okolností archeologické akce a metody.
- Celkový plán výzkumu popř. skica se zaznamenanými situacemi.
- Úplný popis zachycených archeologických situací s připojenou odpovídající dokumentací (kresebnou, fotografickou, geodetickou) a jejím popisem.
- Seznamy získaných artefaktů, ekofaktů a vzorků.

Pokud byly zjištěné archeologické situace z relevantních důvodů dokumentovány jen v omezené míře (např. pouze fotograficky), mělo by toto být ze zápisu v AMČR nebo z přiloženého dokumentu patrné, aby při kontrole před archivací pracovníci archivu mohli rozlišit případy, kdy dokumentace z popsaných důvodů neexistuje, nebo kdy pouze není připojena.
Např. při pořízení pouze fotografické dokumentace by tato měla být opatřena dostatečným popisem (orientace fotografie, popis vrstev, vyznačení hran objektů) a v případě situací, které nejsou z fotografie jasně čitelné, např. i skicou přímo do fotografie.
Zásadou v podobných případech však vždy je, že samotná fotografie nikdy nenahrazuje popis.
Připojený soubor by pak měl mít podobu uceleného dokumentu opatřeného titulní stranou (nemělo by se tedy jednat pouze o připojené fotografie atp.).

Stejně jako v případě plnohodnotné NZ musí být z těchto dokumentů možné **rekonstruovat zjištěné situace v maximální možné míře**.
NZ musí dále korespondovat se zápisem [komponent](pojmy.qmd#komponenty) v kartě [dokumentační jednotky](pojmy.qmd#dokumentační-jednotky) a to až do úrovně kategorií získaných nálezů a vice versa.

## Příklady dobré praxe

### Několik zahloubených objektů

Při plošné skrývce malého rozsahu bylo zachyceno 5 zahloubených archeologických objektů.
Objekty byly kresebně a fotograficky dokumentovány a geodeticky zaměřeny.
Dokument připojený k akci v AMČR bude v takovém případě obsahovat:

- popis okolností archeologické akce;
- metoda výzkumu -- kolik cm bylo skryto, jak byly vybírány objekty, způsob dokumentace, popis metody zaměření;
- celkový plán výzkumu;
- tabulku geodeticky zaměřených bodů;
- fotografickou dokumentaci vč. popisu fotografie a orientace, seznam fotografií (katalog);
- kresebnou dokumentaci zachycených objektů vč. všech formálních náležitostí, seznam výkresů;
- přehled movitých archeologických nálezů/vzorků ideálně formou tabulky, poznámku o jejich uložení, popř. skartaci;
- vyhodnocení projektu, datace prozkoumaných situací;
- odborné posudky (pokud byly provedeny nějaké analýzy).

### Zachycena kulturní vrstva

Při výkopu pro základové pasy rodinného domu byla na profilu výkopu zachycena kulturní vrstva, která byla z důvodů nepříznivých podmínek/BOZP dokumentována pouze fotograficky z hrany výkopu.
V dokumentu připojeném k akci v AMČR bude v tomto případě:

- popis archeologické akce;
- metoda výzkumu vč. jejího odůvodnění (proč není výkres);
- popis a lokalizace zachycené vrstvy (geodeticky zaměřená, zaznamenané do plánu stavby, skica celkové situace atp.);
- fotografie této vrstvy (rozhraní jednotlivých vrstev lze doplnit přímo do fotografie);
- vyhodnocení projektu, datace prozkoumaných situací;
- odborné posudky (pokud byly provedeny).

### Střepy bez archeologické situace

Při výkopu pro inženýrské sítě byl při kontrole zeminy z výkopu nalezen soubor keramických střepů, které byly odebrány a zařazeny do sbírek nebo skartovány.
Ve vlastním výkopu však nebyly zachyceny žádné archeologické objekty ani vrstvy.
Zápis v AMČR bude v takovém případě obsahovat pouze popis archeologické akce s vyplněným popisem komponent podle nalezených střepů a jejich uložení v příslušné instituci, popř. poznámku o skartaci.
V takovém případě není nutné připojovat do karty *Dokumentace* jakýkoliv dokument.
