---
title: Informace o zpracování osobních údajů registrovaných uživatelů 
description: Platné od 29. 4. 2021
date: 2025-08-26
---

::: {.callout-note}

Prosím, věnujte pozornost následujícímu textu, jehož prostřednictvím Vám poskytujeme informace o zpracování Vašich osobních údajů a o právech souvisejících s Vaším využíváním služeb [Archeologického informačního systému České republiky](https://www.aiscr.cz/){.external}, který je provozován: 

- **Archeologickým ústavem AV ČR, Praha, v.v.i.**, IČ 67985912, se sídlem Letenská 4, 118 01 Praha 1 ([https://www.arup.cas.cz](https://www.arup.cas.cz){.external}) a 
- **Archeologickým ústavem AV ČR, Brno, v.v.i.**, IČ 68081758, se sídlem Čechyňská 363/19, 602 00 Brno ([https://www.arub.cz](https://www.arub.cz){.external}).

:::

::: {.callout-tip}

## Zpracování základních osobních údajů při evidenci archeologických výzkumů a odborné bibliografie

Zpracování vybraných osobních údajů je prováděno jako nezbytné pro splnění úkolů ve veřejném zájmu nebo při výkonu veřejné moci, kterými je pověřen *Správce* (Archeologické ústavy AV ČR) v souvislosti s naplňováním [zákona 20/1987 Sb., o státní památkové péči](https://www.zakonyprolidi.cz/cs/1987-20){.external}. 
Zpracování probíhá formou udržování [slovníku osob](/o-systemu/heslare.qmd) (jméno, příjmení, rodné příjmení, rok narození, ORCID ID, Wikidata ID) užívaného při identifikaci osob odborně odpovědných za archeologické výzkumy a při identifikaci autorství související dokumentace a publikací. 
Ke zpracování osobních údajů za tímto účelem dochází z veřejných zdrojů a na základě údajů poskytnutých jednotlivými uživateli.

:::


### Úvodní informace

Jakékoliv nakládání s osobními údaji se řídí platnými právními předpisy, zejména [nařízením Evropského parlamentu a Rady č. 2016/679 ze dne 27. 4. 2016 o ochraně fyzických osob v souvislosti se zpracováním osobních údajů a o volném pohybu těchto údajů a o zrušení směrnice 95/46/ES](https://eur-lex.europa.eu/legal-content/CS/ALL/?uri=CELEX:02016R0679-20160504){.external} (dále jen *„obecné nařízení o ochraně osobních údajů“*) a [zákonem č. 110/2019 Sb., o zpracování osobních údajů](https://www.zakonyprolidi.cz/cs/2019-110){.external} (dále jen *„zákon“*). 
V souladu s ustanovením čl. 13 a následující obecného nařízení o ochraně osobních údajů Vám jako tzv. subjektům údajů poskytujeme následující informace. 
Tento text je veřejný a slouží k Vašemu řádnému informování o rozsahu, účelu, době zpracování osobních údajů a k poučení o Vašich právech v souvislosti s jejich ochranou.


### Kdo je správcem osobních údajů

Společnými správci osobních údajů jsou Archeologický ústav AV ČR, Praha, v.v.i., IČ 67985912, se sídlem Letenská 4, 118 01 Praha 1 a Archeologický ústav AV ČR, Brno, v.v.i., IČ 68081758, se sídlem Čechyňská 363/19, 602 00 Brno (dále jen *„Správce“* či *„Archeologický ústav“*).


### Co jsou osobní údaje

Osobními údaji jsou veškeré informace vztahující se k identifikované či identifikovatelné fyzické osobě (člověku), na základě kterých lze konkrétní fyzickou osobu přímo či nepřímo identifikovat (*subjekt* údajů). 
Mezi osobní údaje tak patří široká škála informací, jako je například jméno, pohlaví, věk a datum narození, osobní stav, fotografie (resp. jakékoliv zobrazení podoby), rodné číslo, místo trvalého pobytu, telefonní číslo, e-mail, údaje o zdravotní pojišťovně, státní občanství, údaje o zdravotním stavu (fyzickém i psychickém), ale také otisk prstu, podpis nebo IP adresa.


### Za jakým účelem a na jakém základě zpracováváme Vaše osobní údaje

Vaše osobní údaje zpracováváme, abychom Vám mohli zajistit řádný provoz služeb Archeologického informačního systému České republiky. 
Při zpracování osobních údajů uživatele jako *subjektu* osobních údajů dle čl. 6 odst. 1 písm. b) obecného nařízení o ochraně osobních údajů je Archeologický ústav v postavení *Správce*. 
Vaše osobní údaje v níže uvedeném rozsahu zpracováváme, pouze aby Vám byl umožněn přístup a využívání služeb Archeologického informačního systému České republiky.

### Rozsah osobních údajů zpracovávaných Správcem

Informujeme Vás, že Vaše osobní údaje jsou zpracovávány v rozsahu Vámi vyplněného registračního formuláře, a to konkrétně v rozsahu:

- jméno,
- příjmení,
- telefonní číslo,
- e-mail,
- heslo,
- IP adresa,
- identifikátor ORCID.

### Doba zpracování osobních údajů

Vaše osobní údaje budeme ukládat po dobu nezbytně nutnou k zajištění fungování systému a naplňování jeho účelu. 
V případě neaktivních a jinak nevyužitých účtů probíhá zpracování maximálně po dobu deseti let. 
Tyto lhůty vyplývají ze zákonných požadavků, potřeb plnění veřejného zájmu a z titulu ochrany zájmu *subjektu*."

### Další informace o zpracování osobních údajů

Osobní údaje *subjektu* údajů jsou zpracovávány automatizovaně v elektronické formě.

Pokud si budete přát, aby Vás kontaktoval určitý odborný pracovník správce, tak za tímto účelem budou danému odbornému pracovníkovi předány osobní údaje nezbytné pro Vaše kontaktování, a to v rozsahu jméno, příjmení, e-mail, telefon.

Vaše osobní údaje nepředáváme a nemáme v úmyslu předat do třetí země nebo mezinárodní organizaci.

<!-- V případě, že do Archeologického informačního systému ČR vložíte o vlastní vůli Váš vlastní záznam, budou u takového záznamu uvedeny Vaše osobní údaje, a to v rozsahu jméno a příjmení.

Vaše osobní údaje, a to v rozsahu jméno a příjmení uvedené u Vámi vloženého záznamu, předáváme do:

- zemí Evropské Unie za účelem agregace dat v infrastrukturách [ARIADNE](https://www.ariadne-research-infrastructure.eu/){.external} a [Europeana](https://www.europeana.eu/){.external};
- zemí Evropské Unie, případně třetích zemí, za účelem přidělení persistentního identifikátoru prostřednictvím organizace [DataCite](https://datacite.org/){.external};
- zemí Evropské Unie prostřednictvím agregace dat prostřednictvím národní implementace iniciativy [EOSC](https://www.eosc.cz/){.external}.

Vyjma výše uvedeného nepředáváme a nemáme v úmyslu předat Vaše osobní údaje do třetí země nebo mezinárodní organizaci. -->


### Poučení o právech subjektů údajů

*Subjekt* údajů má právo požádat *Správce* o poskytnutí informace o zpracování jeho osobních údajů.

*Subjekt* údajů má právo, aby *Správce* bez zbytečného odkladu opravil nepřesné osobní údaje, které se ho týkají. S přihlédnutím k účelům zpracování má subjekt údajů právo na doplnění neúplných osobních údajů, a to i poskytnutím dodatečného prohlášení.

*Subjekt* údajů má právo, aby *Správce* bez zbytečného odkladu vymazal osobní údaje, které se daného *subjektu* údajů týkají, a *Správce* má povinnost osobní údaje bez zbytečného odkladu vymazat, pokud je dán některý z důvodů stanovených obecným nařízením o ochraně osobních údajů nebo zákonem.

*Subjekt* údajů má právo, aby *Správce* omezil zpracování osobních údajů, v případech stanovených obecným nařízením o ochraně osobních údajů nebo zákonem.

V případě, že byste se domnívali, že *Správce* provádí zpracování Vašich osobních údajů v rozporu s ochrannou Vašeho soukromého a osobního života nebo s příslušnými právními předpisy, zejména jsou-li osobní údaje nepřesné s ohledem na účel jejich zpracování, můžete vznést námitku proti zpracování Vašich osobních údajů.

Pokud se *subjekt* údajů domnívá, že došlo k porušení právních předpisů v souvislosti s ochranou jeho osobních údajů, má právo podat stížnost u Úřadu pro ochranu osobních údajů.

::: {.callout-note}

## Zpracování osobních údajů oznamovatelů terénních zásahů

Zpracování osobních údajů poskytnutých při oznamování terénních zásahů ve smyslu [§ 22 odst. 2 zákona č. 20/1987 Sb., o státní památkové péči](https://www.zakonyprolidi.cz/cs/1987-20#p22){.external}, je upraveno samostatně. 
Více informací viz [https://amcr.aiscr.cz/oznameni/](https://amcr.aiscr.cz/oznameni/){.external}

:::
